version: '3.8'

services:
  report-service:
    container_name: report-service-local
    image: report-service-image
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    networks:
      mesx_network:
        ipv4_address: ${CONTAINER_NETWORK_IP}
    volumes:
      - .:/app
      - report_node_modules:/app/node_modules/
    restart: unless-stopped
    command: npm run start:debug
    ports:
      - ${APP_CONTAINER_PORT}:3000
      - 9237:9237

networks:
  mesx_network:
    name: ${MESX_NET_NAME}
    external: true

volumes:
  report_node_modules:
