# docker compose version
version: '3.8'
# all the containers have to declare inside services
services:
  report-service:
    container_name: ${NODE_ENV}-report-service
    image: ${DOCKER_REGISTRY}/snp_smartwms/source/be/report-service:develop
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      mesx-net:
        ipv4_address: ${CONTAINER_NETWORK_IP}
    ports:
      - ${APP_CONTAINER_PORT}:${SERVER_HTTP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
networks:
  mesx-net:
    name: ${MESX_NET_NAME}
    external: true

# save (persist) data
volumes:
  db_data: {}
