version: '3.8'

services:
  report-service:
    container_name: local-report-service
    image: report-service
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    networks:
      mesx-net:
        ipv4_address: ${CONTAINER_NETWORK_IP}
    command: npm run start:dev
    ports:
      - ${APP_CONTAINER_PORT}:${SERVER_HTTP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

networks:
  mesx-net:
    name: ${MESX_NET_NAME}
    external: true
