export enum OrderStatus {
  Pending = 0,
  Confirmed = 1,
  InProgress = 2,
  Approved = 3,
  Completed = 4,
  Reject = 5,
  InReceiving = 6,
  Received = 7,
  Delivered = 8,
  InCollecting = 9,
  Collected = 10,
  Exported = 11,
  RejectReceived = 12,
  InProducing = 13,
  Produced = 14,
  InReturning = 15,
  Returned = 16,
  Stored = 17,
}
