export enum ReportType {
  ITEM_INVENTORY_BELOW_MINIMUM = 1,
  ITEM_INVENTORY_BELOW_SAFE = 2,
  ORDER_TRANSFER_INCOMPLETED = 3,
  ORDER_EXPORT_INCOMPLETED = 4,
  ORDER_IMPORT_INCOMPLETED = 5,
  ITEM_IMPORTED_BUT_NOT_PUT_TO_POSITION = 6,
  ITEM_INVENTORY = 7,
  ORDER_IMPORT_BY_REQUEST_FOR_ITEM = 8,
  INVENTORY = 9,
  ITEM_INVENTORY_IMPORTED_NO_QR_CODE = 10,
  ORDER_EXPORT_BY_REQUEST_FOR_ITEM = 11,
  SITUATION_TRANSFER = 12,
  SITUATION_INVENTORY_PERIOD = 13,
  SITUATION_IMPORT_PERIOD = 14,
  SITUATION_EXPORT_PERIOD = 15,
  AGE_OF_ITEM_STOCK = 16,
  REORDER_QUANTITY = 17,
  TRANSACTION_DETAIL = 18,
}

export enum ActionType {
  IMPORT = 0,
  EXPORT = 1,
}

export const ARR_REPORT_TYPE_CHANGE_FONT_SIZE = [
  ReportType.ORDER_IMPORT_INCOMPLETED,
  ReportType.SITUATION_IMPORT_PERIOD,
  ReportType.SITUATION_EXPORT_PERIOD,
  ReportType.ITEM_IMPORTED_BUT_NOT_PUT_TO_POSITION,
  ReportType.ORDER_TRANSFER_INCOMPLETED,
  ReportType.ORDER_EXPORT_BY_REQUEST_FOR_ITEM,
  ReportType.ITEM_INVENTORY_BELOW_MINIMUM,
  ReportType.ITEM_INVENTORY_BELOW_SAFE,
];
